print '==={:<10}==='.format('ok')
print '==={:_<10}==='.format('ok')
# print '==={:*<10}==='.format('ok')
# print '==={:\'<10}==='.format('ok')
# print '==={:"<10}==='.format('ok')
# print '==={:^<10}==='.format('ok')
# print '==={:^^<10}==='.format('ok')
# print '==={:^^<10}==='.format('ok')
print '==={:.6}==='.format('okokok')
print '===%.6s===' % ('welcome')
print '==={:.6}==='.format('welcome')
